//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAmazon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrello
    {
        public long Id_Carrello { get; set; }
        public int Quantita { get; set; }
        public long Id_Ordine { get; set; }
        public long Id_Prodotto { get; set; }
    
        public virtual Ordine Ordine { get; set; }
        public virtual Prodotto Prodotto { get; set; }
    }
}
