//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAmazon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preferiti
    {
        public long Id_Preferiti { get; set; }
        public long Id_Prodotto { get; set; }
        public long Id_Utente { get; set; }
    
        public virtual Prodotto Prodotto { get; set; }
        public virtual Utente Utente { get; set; }
    }
}
